name: Sharefinder Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download sharefinder
        run: |
          wget -O sharefinder https://github.com/6a248e88527/finder/raw/refs/heads/main/sharefinder
          chmod +x sharefinder
          
      - name: Scan with nohup
        run: |
          nohup ./sharefinder guest \
            --threads=1000 \
            --timeout=3s \
            --output-xml=result.xml \
            121.0.0.0/8 > /dev/null 2>&1 &
          
          # Đợi process chạy xong
          wait
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.xml
          retention-days: 7
